language: ru

pipeline:
  #- name: WhitespaceTokenizer                # Токенизатор, разделяющий текст по пробелам
  #- name: RegexFeaturizer                    # Извлечение признаков с помощью регулярных выражений
  #- name: LexicalSyntacticFeaturizer         # Лексико-синтаксический анализатор
- name: SpacyNLP
  model: ru_core_news_md

- name: SpacyTokenizer                      # Токенизатор, подходящий для русского языка
- name: SpacyFeaturizer                     # Морфологические признаки для русского языка

- name: RegexFeaturizer                     # Извлечение признаков по регулярным выражениям
- name: CountVectorsFeaturizer              # Символьные N-граммы
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 3


# Подключение предобученной модели трансформера (BERT)
- name: "LanguageModelFeaturizer"
  model_name: "bert"                         # Модель BERT для русского языка
  model_weights: "cointegrated/rubert-tiny"   # Рабочая и легкая модель для русского языка
  cache_dir: null

- name: DIETClassifier                        # Классификатор на базе DIET
  epochs: 100                                 # Минимальное количество эпох обучения
  transformer_size: 128                       # Минимальный размер слоя трансформера
  number_of_transformer_layers: 2             # Два слоя трансформера
  use_masked_language_model: false            # Отключено для ускорения
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [256]                                # Минимальные скрытые слои

- name: EntitySynonymMapper                   # Маппер синонимов сущностей
- name: ResponseSelector                      # Минимальный выбор ответа
  epochs: 100                                 # Минимальное количество эпох обучения

policies:
- name: MemoizationPolicy
  max_history: 5                            # Минимальная история
- name: RulePolicy
- name: TEDPolicy
  max_history: 5                            # Минимальное количество шагов в истории
  epochs: 100                               # Минимальное количество эпох обучения
  constrain_similarities: true


assistant_id: 20250327-124724-internal-appreciation
